<a href="https://colab.research.google.com/github/rohan604037/ML-lab/blob/main/lab3/3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import pandas as pd

X,y=make_classification(n_samples=10,n_features=4,n_classes=2)
import numpy as np
def kfold_indices(data, k):
    fold_size = len(data) // k
    indices = np.arange(len(data))
    folds = []
    for i in range(k):
        test_indices = indices[i * fold_size: (i + 1) * fold_size]
        train_indices = np.concatenate([indices[:i * fold_size],
indices[(i + 1) * fold_size:]])
        folds.append((train_indices, test_indices))
    return folds

# Define the number of folds (K)
k = 5

# Get the fold indices
fold_indices = kfold_indices(X, k)

from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier  # import ML  model

# Initialize the machine learning model
model = DecisionTreeClassifier()

# Initialize a list to store the evaluation scores
scores = []

# Iterate through each fold
for train_indices, test_indices in fold_indices:
    X_train, y_train = X[train_indices], y[train_indices]
    X_test, y_test = X[test_indices], y[test_indices]

    print('X_train samples')
    print(X_train)
    print('X_test samples')
    print(X_test)
    # Train the model on the training data
    model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = model.predict(X_test)
    # Calculate the accuracy score for this fold
fold_score = accuracy_score(y_test, y_pred)
# Append the fold score to the list of scores
scores.append(fold_score)
# Calculate the mean accuracy across all folds
mean_accuracy = np.mean(scores)
print("K-Fold Cross-Validation Scores:", scores)
print("Mean Accuracy:", mean_accuracy)

X_train samples
[[-0.50447465 -0.9563746   0.4491091   0.98344291]
 [ 0.95799145 -0.86706133 -0.4460166  -1.78654705]
 [-0.78756843 -1.04615425  0.63337248  1.52182618]
 [-0.21343986  1.28893157 -0.06676909  0.36496343]
 [-0.58836052 -0.96247659  0.50060122  1.14235684]
 [ 1.13327423 -2.37890728 -0.32244718 -2.07257999]
 [ 0.63104638 -2.18606464 -0.04894051 -1.1280806 ]
 [ 0.13665963  0.63734094 -0.17901498 -0.27782858]]
X_test samples
[[-0.22341973  1.30105906 -0.06259198  0.38348133]
 [ 1.21928913 -3.27746038 -0.23805597 -2.20821314]]
X_train samples
[[-0.22341973  1.30105906 -0.06259198  0.38348133]
 [ 1.21928913 -3.27746038 -0.23805597 -2.20821314]
 [-0.78756843 -1.04615425  0.63337248  1.52182618]
 [-0.21343986  1.28893157 -0.06676909  0.36496343]
 [-0.58836052 -0.96247659  0.50060122  1.14235684]
 [ 1.13327423 -2.37890728 -0.32244718 -2.07257999]
 [ 0.63104638 -2.18606464 -0.04894051 -1.1280806 ]
 [ 0.13665963  0.63734094 -0.17901498 -0.27782858]]
X_test samples
[[-0.50447465 -0.